apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-from-scrach-nginx
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: application-from-helm
      # parameters:
      #   - name: replicaCount
      #     value: "3"
      valueFiles:
        - values-qa.yaml
    path: nginx
    repoURL: https://github.com/cgraaaj/argocd-demo.git
    targetRevision: main
